#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $RIZ_REPO == "rizoelxspam" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL01yUml6b2VsL1JpWm9lTFhTcGFtL2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    elif [[ $RIZ_REPO == "RIZOELXSPAM" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL01yUml6b2VsL1JpWm9lTFhTcGFtL2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    elif [[ $RIZ_REPO =~ $regex ]]
    then
        if [[ $RIZ_REPO_BRANCH ]]
        then
            echo "${RIZ_REPO}/archive/${RIZ_REPO_BRANCH}.zip"
        else
            echo "${RIZ_REPO}/archive/main.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL01yUml6b2VsL1JpWm9lTFhTcGFtL2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="rizoelxspam.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    RIZPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $RIZPATH
    echo "  Starting.  RiZoeLXSpam "
    echo "𝙍𝙞𝙕𝙤𝙚𝙇 𝙓 𝙎𝙥𝙖𝙢"

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m RiZoeLXSpam
}

_set_bot
